from pymongo import MongoClient

# MongoDB connection URL
MONGO_URL = "mongodb://localhost:27017"

# Create client
client = MongoClient(MONGO_URL)

# Database
db = client["worklife_balance_db"]

# Collections

# 1️ User account + profile questionnaire
users_collection = db["users"]

# 2️ Weekly check‑in questionnaire responses
weekly_logs_collection = db["weekly_logs"]

# 3️ AI recommendations generated by LLM
recommendations_collection = db["recommendations"]

# 4 ML prediction results
wlb_results_collection = db["wlb_results"]

chat_collection = db["chat_history"]